name: complex_matrix
description: A simple library for complex matrices
version: 0.1.0
author: Edouard Tavinor <edouardtavinor@gmail.com>
homepage: https://github.com/ehrt74/dart_complex_matrix

environment:
  sdk: '>=1.0.0 <3.0.0'
dependencies:
  my_complex: ">=0.0.1 <1.0.0"

dev_dependencies:
  test: '>=0.12.0 <2.0.0'
